base: defaults.yaml

init_checkpoint_dir: outputs/checkpoints_stage1_mixed/best_model
dataset_name: null
train_file: data/qa_multilingual/stage2_vi_train.jsonl
validation_file: data/qa_multilingual/stage2_vi_validation.jsonl

batch_size: 12
epochs: 2
learning_rate: 1.0e-5

output_dir: outputs/checkpoints_stage2_vi
artifact_dir: artifacts/readers/run_best
artifact_name: run_best
